### ISSUE TITLE
Reconnect method

### ISSUE THREAD

**Issue by T3MPN4ME** [lishu/Jock.Net.TcpJson#3]
Hello @lishu, I want detect when my server offline or closed, but library not have **OnConnectionFailed** Event or CallBack for client :no_good_man:

**Also there is another problem in client:**
```
private static void OnStop(TcpJsonClient client)
{
    Console.WriteLine($"{client.Session["Id"]} Disconnected, Reconnecting after 1 second");
    Thread.Sleep(1000);
    client.Start();
}
```

**Output Even when my server is listening:**

> thrown: 'System.InvalidOperationException' in System.dll
> UnhandledException CallBack -> The operation is not allowed on non-connected sockets.

How To Reconnect if failed on `Client.Start()` (Throw socket exception) or OnStop CallBack ?
Can you add those feature to library or do you have any better opinion?

**Comment by lishu** [comment]
1. Because sockets can only really test whether the connection is interrupted when sending data. `TcpJsonClient` has core thread send data, means the broke you can only known in UnhandledException event. or a auto ping just auto send at `PingTimeSpan` delay.
**But you can try `SendRequest` and `OnReceiveRequest`, the like http a request wait a response. if not exception happend, It ensure that the server responds to your request.**
2. **stoped** client can not restart, just create a new instance. (Maybe add reconnect feature in future, But it's not a core feature.)

**Comment by T3MPN4ME** [comment]
OK, I'm waiting for new features :grinning: like:

**Support target framework 3.5**

**TcpJsonClient:**

- OnConnectionFailed CallBack,
- Reconnect Method

**TcpJsonServer:**
**ConnectingEventArgs** -> **Cancel property:** great idea :+1: 
**ConnectedEventArgs**  -> **ServerClient:**
- RemoteIP function
- ClientID instead of `e.ServerClient.Session["ID"] = Guid.NewGuid().ToString();`

I'm not your project manager :smile:, but this is my personal opinion, if you agree , add in the next update, if possible.

**Comment by lishu** [comment]
Good idea.
BTW
1. The `TcpJsonClient` has public `Client` property, This is [`TcpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient?view=netcore-2.0) type who has Socket，So you can get remote ip address and port.
2. No anyone need `ID` or The `Guid` type `ID`, So This Should Be User's Choice.

**Comment by lishu** [comment]
**Why no auto-connection is implemented.**
Because the internal automatic Ping has been achieved, so generally in the server and the client under normal conditions will not be disconnected, if there is a disconnect, the biggest possibility is a code problem, or the server/client actively stop shutting down the connection, usually this time automatically reconnect is done without effort.

**Comment by T3MPN4ME** [comment]
Auto connect with `interval` should be good and it can solve the **ConnectionFailed** problem :+1:
But in any case we need the **OnConnect** / **OnDisconnect** Event ...

**eg:**
I want to disable the chat box or show a message to the user when the server is unavailable ..
or what is the reason for Disconnect? Does not connect to the Internet? or ...

**Please make it easier for your users :))**

**Comment by lishu** [comment]
You can handle it by use `OnStop`, This callback will invoke when any reason core thread stop, One of the reason is socket disconnect.

**Comment by lishu** [comment]
In fact, you can use the `OnStoped` callback to discover connection outages, and if `Start()` is called directly or later in this callback, it will work.

**Comment by T3MPN4ME** [comment]
Thanks for add support **.net 3.5** in update
But still `Start()` Method unresolved :(

**Example code:**
```
TcpJsonServer server = new TcpJsonServer(new IPEndPoint(IPAddress.Any, 2000));
server.Connected += Server_Connected;
//  server.Start(); // if server not available now! and the client wants to start!
```

```
TcpJsonClient client = new TcpJsonClient(new IPEndPoint(IPAddress.Loopback, 2000));
client.UnhandledException += Client_UnhandledException;
client.OnStoped(OnStoped);
try
{
      client.Start(); //Thow exception (no call UnhandledException and not work in try catch)
}
catch
{
      Console.WriteLine("Start() Exception");
}
```

> An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
> Additional information: No connection could be made because the target machine actively refused it
![capture](https://user-images.githubusercontent.com/44739838/48133123-fe166b80-e2aa-11e8-92e9-019e53569900.PNG)

**Comment by lishu** [comment]
It's not the right code. Maybe it's because of my bad English.

var client = new ...
client.OnReiceve.....
client.UnhandledException...
client.OnStoped(c=>{
      // Restart here
      Thread.Sleep(1000);
      c.Start();
});
client.Start()

**Comment by lishu** [comment]
if server is not start, that is not something client can do, check `UnhandledException.ExceptionObject` property check type and deal with it.

**Comment by M4D3V2000** [comment]
No, your English is good
i think you don't understand **what i mean**

### Your above [code](https://github.com/lishu/Jock.Net.TcpJson/issues/3#issuecomment-436618580):
![capture](https://user-images.githubusercontent.com/16842992/48224421-869a1800-e34e-11e8-8995-39e88255360b.PNG)

This happens when i run the project and the **server is not started** ...
It's not a good idea if i should insert the code at `try {} catch {}` :confused:

**Comment by lishu** [comment]
I see what you mean.
But that doesn't seem to be too much of a problem.
Conversely, if my library takes the initiative to retry later without an exception, the user has no idea why there is no error, but is unable to send or receive data.

So I'm afraid you should insert the code at `try {} catch {}`

**Comment by lishu** [comment]
See [Client Connect](https://github.com/lishu/Jock.Net.TcpJson/wiki/Client-Connect) maybe help.

**Comment by M4D3V2000** [comment]
HAHAHAHA Nice Update :ok_hand:
**ConnectionFailed** or `Start()` Exception Problem solved and about **OnConnect** CallBack, I can manage in my server :man_technologist: 

Thanks for your support. (_I will open a lot of issue_ :laughing:)
